import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { MongooseModule } from '@nestjs/mongoose';
import { TestingModule } from './modules/testing/testing.module';
import { CoreModule } from './core/core.module';
import { BlogsModule } from './modules/bloggers-platform/bloggers-platform.module';
import { UsersModule } from './modules/users/users.module';
import { PostsModule } from './modules/bloggers-platform/posts/posts.module';
import { AuthModule } from './modules/auth/auth.module';
import { APP_FILTER, APP_PIPE } from '@nestjs/core';
import { HttpExceptionFilter } from './core/filters/http-exception.filter';
import { ValidationPipe, BadRequestException } from '@nestjs/common';